# Generated by Django 3.2.19 on 2023-06-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='counting',
            field=models.IntegerField(default=0),
        ),
    ]
