# Generated by Django 3.2.19 on 2023-06-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_user_counting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='counting',
            field=models.IntegerField(default=500),
        ),
    ]
