# Generated by Django 3.2.19 on 2023-06-11 10:22

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_user_counting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileimage',
            field=models.ImageField(blank=True, default='/media/img/baseimage.jpg', null=True, upload_to=common.models.image_upload_path),
        ),
    ]
