# Generated by Django 3.2.19 on 2023-06-11 10:23

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_user_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileimage',
            field=models.ImageField(blank=True, default='img/baseimage.jpg', null=True, upload_to=common.models.image_upload_path),
        ),
    ]
