# Generated by Django 3.2.19 on 2023-05-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='filteringmessage',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='roomname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
