# Generated by Django 3.2.19 on 2023-06-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20230527_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='filteringmessage',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(max_length=128),
        ),
    ]
