# Generated by Django 3.2.19 on 2023-06-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chat_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='filteringmessage',
        ),
    ]
