# Generated by Django 3.2.19 on 2023-06-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_chat_filteringmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chatimage',
        ),
    ]
