# Generated by Django 3.2.19 on 2023-06-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_chat_chatimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
