# Generated by Django 3.2.19 on 2023-06-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistfeed',
            name='create_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userfeed',
            name='create_date',
            field=models.DateTimeField(),
        ),
    ]
