# Generated by Django 3.2.19 on 2023-06-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20230608_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistfeed',
            name='vilification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfeed',
            name='vilification',
            field=models.BooleanField(default=False),
        ),
    ]
